api = "0.7"

[buildpack]
  description = "A buildpack for configuring a Memcached session handler for PHP"
  homepage = "https://github.com/paketo-buildpacks/php-memcached-session-handler"
  id = "paketo-buildpacks/php-memcached-session-handler"
  keywords = ["php", "memcached"]
  name = "Paketo PHP Memcached Session Handler Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-memcached-session-handler/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml", "config/php-memcached.ini"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
